# global:
  # envs:
    # need this because it's part of config, but not
    # PD_DELEGATOR_HTTPS_PUBLIC_PORT: "443"
    
# #############################################################
# # pingfederate-admin values
# #############################################################
# pingfederate-admin:
#   enabled: true
#   # container:
#   #   waitFor:
#   #     pingdirectory:
#   #       service: ldaps
#   image:
#     repository: pingidentity
#     name: pingfederate
#     tag: 10.2.0-edge
#     pullPolicy: Always

# #############################################################
# # pingfederate-engine values
# #############################################################
pingfederate-engine:
#   enabled: true
#   image:
#     repository: pingidentity
#     name: pingfederate
#     tag: 10.2.0-edge
#     pullPolicy: Always
#   clustering:
#     autoscaling:
#       enabled: false
  container:
    replicaCount: 1

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  # enabled: true
  # envs:
  #   SERVER_PROFILE_PATH: profiles/pingdirectory
  #   SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd 
  #   MAKELDIF_USERS: "2000"
  container:
    replicaCount: 1

#############################################################
# pingdataconsole values
#############################################################
# pingdataconsole:
#   enabled: true
  # envs:
  #   SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  #   SERVER_PROFILE_PATH: baseline/pingdataconsole
  #   SERVER_PROFILE_BRANCH: master