############################################################
# Ping Identity DevOps values.yaml
############################################################
# The yaml is seperated into 2 major sections:
#  - global - Represents the base set of values that will
#             be used for each product, if that product
#             doesn't override the global values.
#
#  - image  - For every image/product, the values will
#             be merged with the global settings, and
#             take precedence.
############################################################

############################################################
# Global values
############################################################
global:
  addReleaseNameToResource: none
  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      # nginx example
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"
  image:
    repository: pingidentity
    name:
    tag: 2010
    pullPolicy: IfNotPresent
  license:
    secret:
      devOps: devops-secret
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_ADMIN_PATH: profiles/pingfederate_admin
    SERVER_PROFILE_ADMIN_URL: https://github.com/pingdevopsprogram/reference-cicd
    SERVER_PROFILE_PARENT: ADMIN
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
    #changeme to your <release-name>-hostname
    PF_ADMIN_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-admin.ping-devops.com
    PF_ENGINE_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-engine.ping-devops.com
    PF_ADMIN_PUBLIC_PORT: "443"
    PF_ENGINE_PUBLIC_PORT: "443"
    PD_DELEGATOR_PUBLIC_HOSTNAME: sg-dev-fs-pingdelegator.ping-devops.com
    PD_DELEGATOR_PUBLIC_PORT: "443"
    PD_ENGINE_PRIVATE_HOSTNAME: pingdirectory
    PF_ENGINE_PRIVATE_HOSTNAME: pingfederate-engine

#############################################################
# pingfederate-engine values
#############################################################
pingfederate-engine:
  enabled: true
  container:
    waitFor:
      pingdirectory:
        service: ldaps
  envs:
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
    #changeme to your <release-name>-hostname.domain
    PF_ADMIN_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-admin.ping-devops.com
    PF_ENGINE_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-engine.ping-devops.com
    PF_ADMIN_PUBLIC_PORT: "443"
    PF_ENGINE_PUBLIC_PORT: "443"
    PD_DELEGATOR_PUBLIC_HOSTNAME: sg-dev-fs-pingdelegator.ping-devops.com
    PD_DELEGATOR_PUBLIC_PORT: "443"
    PD_ENGINE_PRIVATE_HOSTNAME: pingdirectory
    PF_LOG_LEVEL: DEBUG
    PF_ENGINE_PRIVATE_HOSTNAME: pingfederate-engine
    PF_ADMIN_PORT: "9999"

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_PATH: profiles/pingdirectory
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd 
    # variables that say PUBLIC_HOSTNAME
    #changeme to your <release-name>-hostname
    PF_ADMIN_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-admin.ping-devops.com
    PF_ENGINE_PUBLIC_HOSTNAME: sg-dev-fs-pingfederate-engine.ping-devops.com
    PF_ADMIN_PUBLIC_PORT: "443"
    PF_ENGINE_PUBLIC_PORT: "443"
    PD_DELEGATOR_PUBLIC_HOSTNAME: sg-dev-fs-pingdelegator.ping-devops.com
    PD_DELEGATOR_PUBLIC_PORT: "443"
    PD_ENGINE_PRIVATE_HOSTNAME: pingdirectory
    PF_ENGINE_PRIVATE_HOSTNAME: pingfederate-engine
    MAKELDIF_USERS: "2000"

#############################################################
# pingdataconsole values
#############################################################
pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole
    SERVER_PROFILE_BRANCH: master