############################################################
# Ping Identity DevOps values.yaml
############################################################
# The yaml is seperated into 2 major sections:
#  - global - Represents the base set of values that will
#             be used for each product, if that product
#             doesn't override the global values.
#
#  - image  - For every image/product, the values will
#             be merged with the global settings, and
#             take precedence.
############################################################

############################################################
# Global values
############################################################
global:
  addReleaseNameToResource: append
  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      # nginx example
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"
  image:
    repository: pingidentity
    name:
    tag: 2010
    pullPolicy: IfNotPresent
  license:
    secret:
      devOps: devops-secret
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  container:
    waitFor:
      pingdirectory:
        service: ldaps
  envs:
    SERVER_PROFILE_BASE_PATH: profiles/pingfederate
    SERVER_PROFILE_BASE_URL: https://github.com/pingdevopsprogram/reference-cicd
    SERVER_PROFILE_PARENT: BASE
    SERVER_PROFILE_PATH: profiles/pingfederate_admin
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
## REMOVE ONCE CHART IS UPDATED
  services:
    https:
      servicePort: 9999
      containerPort: 9999
      ingressPort: 443
      dataService: true
    clusterbind:
      servicePort: 7600
      containerPort: 7600
      clusterService: true
    clusterfail:
      servicePort: 7700
      containerPort: 7700
      clusterService: true
    clusterExternalDNSHostname:

#############################################################
# pingfederate-engine values
#############################################################
pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
    PF_LOG_LEVEL: DEBUG
## REMOVE ONCE CHART IS UPDATED
  services:
    https:
      servicePort: 9031
      containerPort: 9031
      ingressPort: 443
      dataService: true
    clusterbind:
      servicePort: 7600
      containerPort: 7600
      clusterService: true
    clusterfail:
      servicePort: 7700
      containerPort: 7700
      clusterService: true
    clusterExternalDNSHostname:

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_PATH: profiles/pingdirectory
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd 
    MAKELDIF_USERS: "2000"

#############################################################
# pingdataconsole values
#############################################################
pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole
    SERVER_PROFILE_BRANCH: master